#!/usr/bin/env bash

# +--------+
# | System |
# +--------+
alias bigf= 'find / -xdev -type f -size +500M'  # display "big" files > 500M

# +-----+
# | X11 |
# +-----+
alias xpropc='xprop | grep WM_CLASS' # display xprop class

# +-----+
# | Zsh |
# +-----+
alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index # directory stack

# +----+
# | ls |
# +----+
alias ls='ls --color=auto'
alias ll='exa -alhF --icons'
alias la='ls -A'
alias l='exa -F'

# +----+
# | cp |
# +----+
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'

# +------+
# | grep |
# +------+
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# +------+
# | xlip |
# +------+
alias cb='xclip -sel clip'

# +------+
# | ping |
# +------+
alias pg='ping 8.8.8.8'

# +-----+
# | bat |
# +-----+
alias batl='bat --paging=never -l log'

# +--------+
# | pacman |
# +--------+
alias paci='sudo pacman -S --needed'      # install
alias pacs='pacman -Ss'
alias pacro='pacman -Rns $(pacman -Qtdq)'
alias pacrl='rm /var/lib/pacman/db.lck'   # pacman remove locks
alias pacclean='sudo paccache -vrk2 && sudo paccache -vruk0'
alias pacawk='pacman -Qet | awk '{print $1}''
alias pacinfo='pacman -Qi | grep'
# +-----+
# | yay |
# +-----+
alias yayi='yay -S --needed' # install
alias yayhi='yay -Ql'        # Yay Has Installed - what files where installed in a package
alias yays='yay -Ss'         # search
alias yayr='yay -Rns'        # remove package but not dependencies
alias yayls="yay -Qe"

# +--------+
# | netctl |
# +--------+
alias wifi='sudo wifi-menu -o'

# +--------+
# | Neovim |
# +--------+
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias dvim="vim -u /usr/share/nvim/archlinux.vim" # nvim with default config
alias nvimc='rm -I $VIMCONFIG/swap/*'             # clean nvim swap file
alias nvimcu='rm -I $VIMCONFIG/undo/*'            # clean the vim undo
alias nviml='nvim -w $VIMCONFIG/vimlog "$@"'      # log the keystrokes
alias nvimn='nvim --noplugin -u NONE'             # launch nvim without any plugin or config

# +-----+
# | Git |
# +-----+
alias gcl='git clone'
alias gs='git status'
alias gss='git status -s'
alias ga='git add'
alias gp='git push'
alias gpraise='git blame'
alias gpo='git push origin'
alias gpt='git push --tag'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'             # display remote branch
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d" # Delete local branch merged with master
alias gsub="git submodule update --remote" # pull submodules
alias dif="git diff --no-index" # Diff two files even if not in git repo! Can add -w (don't diff whitespaces)

# Folders
alias work="$HOME/workspace"
alias doc="$HOME/Documents"
alias dow="$HOME/Downloads"

# +--------+
# | Ranger |
# +--------+
alias rg='. ranger'

